sudo: required
os:
- linux
services:
- docker
language: node_js
node_js:
- 12.13.1
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
  - "$HOME/.cache"
env:
  global:
  - NODE_VERSION=12.13.1
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
  - JHI_DISABLE_WEBPACK_LOGS=true
  - NG_CLI_ANALYTICS="false"
  - MAVEN_USER_HOME=$HOME/.m2/repository/
  - secure: BuYh1QCR5bD5mfS7DWdNVUSBtubVMGerv7LhNElGrCRfqlFADkbkGogjmODjVHPMxj3IgRJESbEo0YLRLGdNGd1OuCFW/qENsErWHOFDzMhsE4/C5bQLTBL0lcdzTK3G5oOPJ6pb47VY6WrHUc/4tWcerzhsNDy7E5isgZyOm+Ncf2p3FGJ5Ie89gPdLeErgDTmMVwth+d1JGiaCAvR70HwGOXjMEhFi5kzBNg+PCjVvopbIscgRtJtAMEvrN4slPUNV8VBmX97P4l5p1nP1xbgS8g9jkcscy/rqqrBE79P70PliYxuXLUzK5o2X6dlYGIFXekXidADWr64y3W2EegCR2gnEVy+ExtwZRbjlhLW14I78jIVOyYEqNvJ3EpGM+fQz8A/03AvmKEwFTy6H39tRl3RlVOODWo9K39vkQNdrks/xYBJItep+SGLcjM0mlvY2GVTom7DIeWwba1fVF+73cRrUS7Bn8JblM0n0DAbse3BS1/3B56nSKWEh6zGMXWRK4x82KjQgawcFZCe6UCKfu+08LjQRDA/T1gb7M6vJDNBRv+8y85BRXUNXSA9uXZ8wo5fyUW68DQebfIfULEUDxIn3BUTqHvXLEhDnS6Q0rm76j4jBZnbwthbWWrbj5fmSwRNFcQzNQCTgBtZCwCVYF4MtjkOUPC0MosFjb84=
before_install:
- echo $super_secret_password | gpg --passphrase-fd 0 client-secret.json.gpg
- |
  if [[ $JHI_JDK = '8' ]]; then
    echo '*** Using OpenJDK 8'
  else
    echo '*** Using OpenJDK 11 by default'
    sudo add-apt-repository ppa:openjdk-r/ppa -y
    sudo apt-get update -q
    sudo apt-get install -y openjdk-11-jdk -y
    sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
    java -version
  fi
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- nvm install $NODE_VERSION
- npm install -g npm
- node -v
- npm -v
install:
- npm install
script:
- chmod +x mvnw
- "./mvnw -ntp checkstyle:check"
- "./mvnw -ntp clean verify"
- "./mvnw -ntp com.github.eirslett:frontend-maven-plugin:npm -Dfrontend.npm.arguments='run
  test' -Dmaven.repo.local=$MAVEN_USER_HOME"
- "./mvnw -ntp verify -Pprod -DskipTests"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
