sudo: required
os:
- linux
services:
- docker
language: node_js
node_js:
- 12.13.1
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
  - "$HOME/.cache"
env:
  global:
  - NODE_VERSION=12.13.1
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
  - JHI_DISABLE_WEBPACK_LOGS=true
  - NG_CLI_ANALYTICS="false"
  - MAVEN_USER_HOME=$HOME/.m2/repository/
  - secure: 37hjFzECw3vH5JNjVksCTtO2FFoyJYOc7K2dfkPoFEGtW0xtG3Jd/QFzdB74gn3LAhULC6vntnVX0/b6Jfm27tB5Tqmxeea1BZ6BBhOw1wTyQ2CqiDwFQKU41aRN6iQ8Dd32argXB5rKyqR2ZFmzcAiBdWp8IlAwvM+p6Px3gdAtQxkmuXYW6I9bfZQ09lqnRuDUW9g9aJJOI3lLPTabtvsp43QBhXx0oko+8moXqcV+rC3Nw+C1YJJxuSFQxDCVhUpIk3ltEoxpV0/Ke0naFlXzQgpHIpwCHHTbODGS73Kn9NwNIUcLYzzcLjc0ITTk82XEXTpx9aW798GEA0UtfEhFAX81yRDpBoT/zLiweJQMINGYDglSMfnDwyxOpAJm9I7z0BFP2aiVP6kPbSL/RQI8H/ZkQW68SBZ80FB1fZ+bdGs3tkGLgAcAVswwdcraVqbPpDYr/PimmvoxB2TcXROmZFk/rfrmweNYyosxU17jMTDeIeLOjq3IrSw/ptS0pmUKdlTS5+I4VKALbCg9d6dKCjHP0WEqCinfTGzkdeUwKEK05XmpTR8sQQv0DtuRNwdkfZfbibLPxLxRAj3GCO9o5lhP/8+tc8rwMVUg+Rckz0uCDJLwIe4v7CwL9KDzL9DpwsYolVTRgNTW76QXVWdW6Hnjh3F9K7Eou9dc0Zs=
before_install:
  -in client-secret.json.enc -out client-secret.json -d
- |
  if [[ $JHI_JDK = '8' ]]; then
    echo '*** Using OpenJDK 8'
  else
    echo '*** Using OpenJDK 11 by default'
    sudo add-apt-repository ppa:openjdk-r/ppa -y
    sudo apt-get update -q
    sudo apt-get install -y openjdk-11-jdk -y
    sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
    java -version
  fi
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- nvm install $NODE_VERSION
- npm install -g npm
- node -v
- npm -v
- echo $super_secret_password | gpg --passphrase-fd 0 client-secret.json
install:
- npm install
script:
- chmod +x mvnw
- "./mvnw -ntp checkstyle:check"
- "./mvnw -ntp clean verify"
- "./mvnw -ntp com.github.eirslett:frontend-maven-plugin:npm -Dfrontend.npm.arguments='run
  test' -Dmaven.repo.local=$MAVEN_USER_HOME"
- "./mvnw -ntp verify -Pprod -DskipTests"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
