# ========================================================================
# App Engine Configuration.
# Full reference is available at:
# https://cloud.google.com/appengine/docs/standard/java11/config/appref
# ========================================================================

runtime: java11
instance_class: F4
service: default
handlers:
- url: /(.*)
  script: auto
  secure: always
automatic_scaling:
  min_instances: 1
  max_instances: 0
entrypoint: java -Dthin.root=. -jar bugtrackerjhipster-0.0.1-SNAPSHOT.jar
beta_settings:
    cloud_sql_instances: halogen-rarity-267815:us-central1:bugtrackerjhipster
